spring.application.name=vsBFF
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/43341e84-316b-40a7-a02f-5c94afd3d730/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://3666de5f-f393-474b-a2b8-e9140225e3af